# Generated by Django 6.0.6 on 2026-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('product_type', models.CharField(choices=[('stock', 'Stock item'), ('custom', 'Custom / special order')], default='stock', max_length=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
