# Generated by Django 6.0.6 on 2026-06-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_custom_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
