# Generated by Django 6.0.6 on 2026-06-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_colour_orderitem_custom_name_orderitem_custom_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='custom_type',
        ),
        migrations.AddField(
            model_name='customtype',
            name='max_images',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customtype',
            name='min_images',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='colours',
            field=models.ManyToManyField(blank=True, to='store.colour'),
        ),
        migrations.CreateModel(
            name='CustomOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.orderitem')),
            ],
        ),
    ]
