# Generated by Django 6.0.6 on 2026-06-30 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_orderitem_colour_remove_orderitem_custom_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customtype'),
        ),
    ]
